### ISSUE TITLE
apidoc plugin no longer exists

### ISSUE THREAD

**Issue by egonzalezpozega** [apigee/docker-apigee-drupal-kickstart#7] opened 2020-09-18 17:57 UTC
It looks like it's trying to install a plugin that no longer exists. The apidoc plugin. After removing the yaml configuration file for that plugin I was able to continue with the deployment. Here's the error message: 
```

Step 29/32 : RUN ../vendor/drush/drush/drush cim --partial --source=$(pwd)/config
 ---> Running in d922b968ed9c
+------------+------------------------------------+-----------+
| Collection | Config                             | Operation |
+------------+------------------------------------+-----------+
|            | rest.resource.entity.developer_app | Create    |
|            | rest.resource.entity.developer     | Create    |
|            | rest.resource.entity.apiproduct    | Create    |
|            | rest.resource.entity.apidoc        | Create    |
|            | rest.resource.entity.node          | Update    |
+------------+------------------------------------+-----------+
 [notice] Synchronized configuration: create rest.resource.entity.developer_app.
 [notice] Synchronized configuration: create rest.resource.entity.developer.
 [notice] Synchronized configuration: create rest.resource.entity.apiproduct.
 [notice] Synchronized configuration: create rest.resource.entity.apidoc.
 [notice] Synchronized configuration: update rest.resource.entity.node.
 [notice] Finalizing configuration synchronization.
 [error]  Drupal\Core\Config\ConfigException: Errors occurred during import in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 343 of /var/www/portal/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php). 

In ConfigImportCommands.php line 357:
                                                                               
  The import failed due to the following reasons:                              
  Unexpected error during import with operation create for rest.resource.enti  
  ty.apidoc: The &quot;entity:apidoc&quot; plugin does not exist. Valid plugi  
  n IDs for Drupal\rest\Plugin\Type\ResourcePluginManager are: dblog, file:up  
  load, entity:developer_app, entity:api_product, entity:developer, entity:bl  
  ock, entity:block_content_type, entity:block_content, entity:comment_type,   
  entity:comment, entity:contact_message, entity:contact_form, entity:editor,  
   entity:field_config, entity:field_storage_config, entity:file, entity:filt  
  er_format, entity:image_style, entity:key_config_override, entity:key, enti  
  ty:media, entity:media_type, entity:menu_link_content, entity:node_type, en  
  tity:node, entity:path_alias, entity:rdf_mapping, entity:responsive_image_s  
  tyle, entity:rest_resource_config, entity:search_page, entity:shortcut, ent  
  ity:shortcut_set, entity:action, entity:menu, entity:taxonomy_term, entity:  
  taxonomy_vocabulary, entity:tour, entity:user, entity:user_role, entity:pat  
  hauto_pattern, entity:view, entity:paragraph, entity:paragraphs_type, entit  
  y:entity_view_mode, entity:entity_form_display, entity:entity_form_mode, en  
  tity:entity_view_display, entity:date_format, entity:base_field_override, u  
  ser_registration                                                             
 
```
And the file in questions is this one: rest.resource.entity.apidoc.yml

**Comment by laughingbiscuit** [comment] 2021-03-22 20:06
thanks - i couldnt reproduce this so looks resolved by the recent changes

**Closed by laughingbiscuit** 2021-03-22 20:06 UTC
